# Generated by Django 5.1.1 on 2024-09-22 09:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="payment_id",
            new_name="stripe_id",
        ),
    ]
