# Generated by Django 5.1.1 on 2024-09-22 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_rename_payment_id_payment_stripe_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
