# Generated by Django 5.1.1 on 2024-09-23 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_payment_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='paid_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
