# Generated by Django 4.2 on 2024-09-29 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_payment_paid_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='user_profile',
        ),
        migrations.AddField(
            model_name='payment',
            name='county',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='payment',
            name='full_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(default='', editable=False, max_length=32),
        ),
        migrations.AddField(
            model_name='payment',
            name='phone_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='postcode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='street_address1',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='payment',
            name='street_address2',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='payment',
            name='town_or_city',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='payment',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
