# Generated by Django 4.2 on 2024-10-07 14:04

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_remove_payment_user_profile_payment_county_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='country',
            field=django_countries.fields.CountryField(default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='payment',
            name='county',
            field=models.CharField(blank=True, default='', max_length=80, null=True),
        ),
    ]
