# Generated by Django 4.2 on 2024-10-15 15:41

import ckeditor.fields
from django.db import migrations, models
import payments.models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_alter_payment_payment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(default=payments.models.Payment._generate_payment_id, editable=False, max_length=32),
        ),
    ]
