# Generated by Django 4.2 on 2024-10-15 15:57

from django.db import migrations, models
import payments.models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_alter_payment_description_alter_payment_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(default=payments.models.Payment._generate_payment_id, editable=False, max_length=32),
        ),
    ]
