# Generated by Django 4.2 on 2024-10-03 12:02

from django.db import migrations, models
import services.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('lead', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to=services.models.ServicesBanner.get_path)),
                ('alt_text', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ServicesCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('lead', models.CharField(max_length=500)),
                ('icon', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='ServicesContextBannerOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('lead', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to=services.models.ServicesContextBannerOne.get_path)),
                ('alt_text', models.CharField(max_length=100)),
                ('stat_one', models.CharField(max_length=100)),
                ('stat_one_description', models.CharField(max_length=500)),
                ('stat_two', models.CharField(max_length=100)),
                ('stat_two_description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ServicesContextBannerTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('lead', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to=services.models.ServicesContextBannerTwo.get_path)),
                ('alt_text', models.CharField(max_length=100)),
                ('stat_one', models.CharField(max_length=100)),
                ('stat_one_description', models.CharField(max_length=500)),
                ('stat_two', models.CharField(max_length=100)),
                ('stat_two_description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ServicesHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('lead', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to=services.models.ServicesHero.get_path)),
                ('alt_text', models.CharField(max_length=100)),
            ],
        ),
    ]
