# Generated by Django 4.2 on 2024-09-25 16:11

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_article_thumb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body_image',
            field=models.ImageField(default='default.png', upload_to=blog.models.Article.get_path),
        ),
        migrations.AlterField(
            model_name='article',
            name='slider_image_four',
            field=models.ImageField(default='default.png', upload_to=blog.models.Article.get_path),
        ),
        migrations.AlterField(
            model_name='article',
            name='slider_image_one',
            field=models.ImageField(default='default.png', upload_to=blog.models.Article.get_path),
        ),
        migrations.AlterField(
            model_name='article',
            name='slider_image_three',
            field=models.ImageField(default='default.png', upload_to=blog.models.Article.get_path),
        ),
        migrations.AlterField(
            model_name='article',
            name='slider_image_two',
            field=models.ImageField(default='default.png', upload_to=blog.models.Article.get_path),
        ),
        migrations.AlterField(
            model_name='article',
            name='thumb',
            field=models.ImageField(default='default.png', upload_to=blog.models.Article.get_path),
        ),
    ]
