# Generated by Django 4.2 on 2024-10-15 10:25

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_article_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body_continued',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
