# Generated by Django 4.2 on 2024-10-10 13:11

from django.db import migrations, models
import service.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('hero_title', models.CharField(max_length=100)),
                ('hero_image', models.ImageField(upload_to=service.models.ServicesPage.get_path)),
                ('banner_image', models.ImageField(upload_to=service.models.ServicesPage.get_path)),
                ('banner_alt_text', models.CharField(max_length=100)),
                ('highlight_one_title', models.CharField(max_length=100)),
                ('highlight_one_lead', models.CharField(max_length=500)),
                ('highlight_one_image', models.ImageField(upload_to=service.models.ServicesPage.get_path)),
                ('highlight_one_alt_text', models.CharField(max_length=100)),
                ('highlight_two_title', models.CharField(max_length=100)),
                ('highlight_two_lead', models.CharField(max_length=500)),
                ('highlight_two_image', models.ImageField(upload_to=service.models.ServicesPage.get_path)),
                ('highlight_two_alt_text', models.CharField(max_length=100)),
                ('service_info_one_title', models.CharField(max_length=100)),
                ('service_info_one_lead', models.CharField(max_length=500)),
                ('service_info_one_image', models.ImageField(upload_to=service.models.ServicesPage.get_path)),
                ('service_info_one_alt_text', models.CharField(max_length=100)),
                ('service_info_two_title', models.CharField(max_length=100)),
                ('service_info_two_lead', models.CharField(max_length=500)),
                ('service_info_two_image', models.ImageField(upload_to=service.models.ServicesPage.get_path)),
                ('service_info_two_alt_text', models.CharField(max_length=100)),
            ],
        ),
    ]
