# Generated by Django 4.2 on 2024-10-10 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicespage',
            name='service_info_one_lead',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='servicespage',
            name='service_info_two_lead',
            field=models.TextField(),
        ),
    ]
