# Generated by Django 4.2 on 2024-10-11 09:00

from django.db import migrations, models
import service.models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_servicespage_service_info_one_lead_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicespage',
            name='banner_image',
            field=models.ImageField(default='default.png', upload_to=service.models.ServicesPage.get_path),
        ),
        migrations.AlterField(
            model_name='servicespage',
            name='hero_image',
            field=models.ImageField(default='default.png', upload_to=service.models.ServicesPage.get_path),
        ),
        migrations.AlterField(
            model_name='servicespage',
            name='highlight_one_image',
            field=models.ImageField(default='default.png', upload_to=service.models.ServicesPage.get_path),
        ),
        migrations.AlterField(
            model_name='servicespage',
            name='highlight_two_image',
            field=models.ImageField(default='default.png', upload_to=service.models.ServicesPage.get_path),
        ),
        migrations.AlterField(
            model_name='servicespage',
            name='service_info_one_image',
            field=models.ImageField(default='default.png', upload_to=service.models.ServicesPage.get_path),
        ),
        migrations.AlterField(
            model_name='servicespage',
            name='service_info_two_image',
            field=models.ImageField(default='default.png', upload_to=service.models.ServicesPage.get_path),
        ),
    ]
