# Generated by Django 4.2 on 2024-10-14 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_servicespage_list_item_four_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicespage',
            name='hero_subtitle',
            field=models.CharField(default=111, max_length=200),
            preserve_default=False,
        ),
    ]
