# Generated by Django 5.1.1 on 2024-09-22 08:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0002_alter_review_user_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="user_img",
            field=models.ImageField(default="default.png", upload_to="reviews"),
        ),
    ]
