# Generated by Django 5.1.1 on 2024-09-16 14:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="read",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
