# Generated by Django 4.2 on 2024-09-30 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_message_read'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homepage_about_title', models.CharField(max_length=100)),
                ('homepage_about_lead', models.CharField(max_length=200)),
                ('homepage_about_subtitle', models.CharField(max_length=100)),
                ('homepage_about_paragraph_one', models.TextField()),
                ('homepage_about_paragraph_two', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HomePageHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(max_length=50)),
                ('hero_subtitle', models.TextField(max_length=200)),
                ('hero_image', models.ImageField(upload_to='home/')),
                ('hero_list_one', models.CharField(max_length=100)),
                ('hero_list_two', models.CharField(max_length=100)),
                ('hero_list_three', models.CharField(max_length=100)),
                ('hero_list_four', models.CharField(max_length=100)),
                ('data_one_value', models.IntegerField()),
                ('data_one_title', models.CharField(max_length=50)),
                ('data_two_value', models.IntegerField()),
                ('data_two_title', models.CharField(max_length=50)),
                ('data_three_value', models.IntegerField()),
                ('data_three_title', models.CharField(max_length=50)),
            ],
        ),
    ]
