# Generated by Django 4.2 on 2024-09-30 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepageabout_homepagehero'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepageabout',
            name='homepage_about_image',
            field=models.ImageField(default=1, upload_to='cms/home/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='homepagehero',
            name='hero_image',
            field=models.ImageField(upload_to='cms/home/'),
        ),
    ]
