# Generated by Django 4.2 on 2024-10-01 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepageabout_homepage_about_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepageabout',
            name='homepage_about_image',
            field=models.ImageField(default='default.png', upload_to='cms/home/'),
        ),
        migrations.AlterField(
            model_name='homepageabout',
            name='homepage_about_lead',
            field=models.CharField(default='Enter a Lead', max_length=200),
        ),
        migrations.AlterField(
            model_name='homepageabout',
            name='homepage_about_paragraph_one',
            field=models.TextField(default='Enter a Paragraph'),
        ),
        migrations.AlterField(
            model_name='homepageabout',
            name='homepage_about_paragraph_two',
            field=models.TextField(default='Enter a Paragraph'),
        ),
        migrations.AlterField(
            model_name='homepageabout',
            name='homepage_about_subtitle',
            field=models.CharField(default='Enter a Subtitle', max_length=100),
        ),
        migrations.AlterField(
            model_name='homepageabout',
            name='homepage_about_title',
            field=models.CharField(default='Enter a Title', max_length=100),
        ),
    ]
