# Generated by Django 4.2 on 2024-10-02 10:47

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_homepagesliderimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagesliderimages',
            name='image',
            field=models.ImageField(upload_to=home.models.HomePageSliderImages.get_path),
        ),
    ]
