# Generated by Django 4.2 on 2024-10-02 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_homepagesliderimages_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HomePageFAQs',
            new_name='HomePageFAQ',
        ),
    ]
