# Generated by Django 4.2 on 2024-10-02 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_rename_homepagefaqs_homepagefaq'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePagePanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=100)),
                ('paragraph', models.TextField()),
            ],
        ),
    ]
