# Generated by Django 4.2 on 2024-10-02 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_homepagepanel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagepanel',
            name='icon',
            field=models.CharField(max_length=500),
        ),
    ]
