# Generated by Django 4.2 on 2024-10-02 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_homepagepanel_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagepanel',
            name='icon',
            field=models.CharField(max_length=1000),
        ),
    ]
