# Generated by Django 4.2 on 2024-10-07 11:11

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_homepagepanel_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagehero',
            name='hero_image_alt',
            field=models.CharField(default='Enter an alt text', max_length=100),
        ),
        migrations.AddField(
            model_name='homepagehero',
            name='hero_image_mobile',
            field=models.ImageField(default='default.png', upload_to=home.models.HomePageHero.get_path),
        ),
        migrations.AlterField(
            model_name='homepagehero',
            name='hero_image',
            field=models.ImageField(upload_to=home.models.HomePageHero.get_path),
        ),
    ]
