# Generated by Django 4.2 on 2024-10-08 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_homepagehero_hero_image_alt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagepanel',
            name='icon',
            field=models.TextField(),
        ),
    ]
