# Generated by Django 4.2 on 2024-10-11 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_remove_homepagepanel_icon_homepagepanel_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagepanel',
            name='link_to',
            field=models.CharField(default='#', max_length=100),
        ),
    ]
