# Generated by Django 4.2 on 2024-10-12 13:45

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_remove_homepagehero_hero_image_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(editable=False, max_length=100)),
                ('hero_title', models.CharField(max_length=100)),
                ('hero_subtitle', models.TextField(max_length=200)),
                ('hero_image', models.ImageField(upload_to=home.models.AboutPage.get_path)),
                ('body_title', models.CharField(max_length=100)),
                ('body_subtitle', models.TextField(max_length=500)),
                ('body_text', models.TextField()),
                ('body_image', models.ImageField(upload_to=home.models.AboutPage.get_path)),
                ('body_image_alt', models.CharField(default='Enter an alt text', max_length=100)),
            ],
        ),
    ]
