# Generated by Django 4.2 on 2024-10-13 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_aboutpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
