# Generated by Django 4.2 on 2024-10-02 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_sliderimages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SliderImages',
        ),
    ]
